name: DTInsight_CI

permissions:
  contents: write

on:
  push:
    branches:
      - test-actions
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
    - uses: actions/checkout@v2

    - name: Download DTInsight executable
      run: |
        curl -L -o DTInsight_v0.0.2.tar.gz -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://github.com/oakeslab-polymtl/DTInsight/releases/download/v0.0.2/DTInsight_v0.0.2.tar.gz
        tar -xzvf DTInsight_v0.0.2.tar.gz
        file DTInsight.x86_64
        ls -l DTInsight.x86_64
    
    - name: Set execute permissions for the Godot binary
      run: chmod +x ./DTInsight.x86_64
    
    - name: Run Godot and trigger screenshot
      run: |
        # Start virtual display
        xvfb-run --server-args="-screen 0 1024x768x24" ./DTInsight.x86_64 -- --ci-mode &
        sleep 5 # Give time for the HTTP server to start

        # Send HTTP request to trigger screenshot
        curl -s http://localhost:9090
